version: '3'
services:
    dachs:
        container_name: dachs-server
        build:
            context: ./dockerfiles/server_dachs
        image: "dachs-server"
        tty: true
        network_mode: 'bridge'
        ports:
            - '8080:8080'
        links:
            - postgres
        depends_on:
            - postgres
    postgres:
        container_name: dachs-postgres
        build:
            context: ./dockerfiles/server_postgres
        image: "dachs-postgres"
        tty: true
        network_mode: 'bridge'
