version: '3'
services:
    dachs:
        container_name: dachs-server
        build:
            context: ./dockerfiles/dachs_server
        image: gavodachs/server
        tty: true
        network_mode: 'bridge'
        ports:
            - '8080:8080'
        links:
            - postgres
        depends_on:
            - postgres
    postgres:
        container_name: dachs-postgres
        build:
            context: ./dockerfiles/postgres_server
        image: gavodachs/postgres
        tty: true
        network_mode: 'bridge'
