version: '3'
services:
    dachs:
        image: "dachs-server"
        container_name: dachs-server
        # build:
        #     context: ./dockerfiles/server_dachs
        tty: true
        network_mode: 'bridge'
        ports:
            - '8080:8080'
        links:
            - postgres
        depends_on:
            - postgres
    postgres:
        image: "dachs-postgres"
        container_name: dachs-postgres
        # build:
        #     context: ./dockerfiles/server_postgres
        tty: true
        network_mode: 'bridge'
